CREATE TABLE club (
                      id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                      name VARCHAR(255) NOT NULL,
                      state_acronym VARCHAR(2) NOT NULL,
                      created_on DATE NOT NULL,
                      is_active BOOLEAN,
                      PRIMARY KEY (id),
                      UNIQUE (name, state_acronym)
);