CREATE TABLE stadium (
                         id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                         name VARCHAR(255) NOT NULL,
                         state_acronym VARCHAR(2) NOT NULL,
                         cep VARCHAR(9) NOT NULL,
                         city VARCHAR(255) NOT NULL,
                         street VARCHAR(255) NOT NULL,
                         PRIMARY KEY (id),
                         UNIQUE (name, state_acronym)
);