CREATE TABLE matches (
                         id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                         home_club_id BIGINT,
                         away_club_id BIGINT,
                         home_club_number_of_goals BIGINT,
                         away_club_number_of_goals BIGINT,
                         stadium_id BIGINT,
                         match_date TIMESTAMP,
                         PRIMARY KEY (id),
                         FOREIGN KEY (home_club_id) REFERENCES club(id),
                         FOREIGN KEY (away_club_id) REFERENCES club(id),
                         FOREIGN KEY (stadium_id) REFERENCES stadium(id)
);